version: '3'
services:  
  redis01:
    image: redis
    container_name: redis01
    restart: always
    ports:
      - 6379:6379
      - 16379:16379
    entrypoint: [redis-server, /etc/redis/redis.conf, --port, "6379", --cluster-announce-ip, "10.222.60.182", --cluster-announce-port, "6379", --cluster-announce-bus-port, "16379"]
    volumes:
      - /home/dev/redis/redis.conf:/etc/redis/redis.conf
  redis02:
    image: redis
    container_name: redis02
    restart: always
    ports:
      - 6380:6380
      - 16380:16380
    entrypoint: [redis-server, /etc/redis/redis.conf, --port, "6380", --cluster-announce-ip, "10.222.60.182", --cluster-announce-port, "6380", --cluster-announce-bus-port, "16380"]
    volumes:
      - /home/dev/redis/redis.conf:/etc/redis/redis.conf
  redis03:
    image: redis
    container_name: redis03
    restart: always
    ports:
      - 6381:6381
      - 16381:16381
    entrypoint: [redis-server, /etc/redis/redis.conf, --port, "6381", --cluster-announce-ip, "10.222.60.182", --cluster-announce-port, "6381", --cluster-announce-bus-port, "16381"]
    volumes:
      - /home/dev/redis/redis.conf:/etc/redis/redis.conf
  redis04:
    image: redis
    container_name: redis04
    restart: always
    ports:
      - 6382:6382
      - 16382:16382
    entrypoint: [redis-server, /etc/redis/redis.conf, --port, "6382", --cluster-announce-ip, "10.222.60.182", --cluster-announce-port, "6382", --cluster-announce-bus-port, "16382"]
    volumes:
      - /home/dev/redis/redis.conf:/etc/redis/redis.conf
  redis05:
    image: redis
    container_name: redis05
    restart: always
    ports:
      - 6383:6383
      - 16383:16383
    entrypoint: [redis-server, /etc/redis/redis.conf, --port, "6383", --cluster-announce-ip, "10.222.60.182", --cluster-announce-port, "6383", --cluster-announce-bus-port, "16383"]
    volumes:
      - /home/dev/redis/redis.conf:/etc/redis/redis.conf
  redis06:
    image: redis
    container_name: redis06
    restart: always
    ports:
      - 6384:6384
      - 16384:16384
    entrypoint: [redis-server, /etc/redis/redis.conf, --port, "6384", --cluster-announce-ip, "10.222.60.182", --cluster-announce-port, "6384", --cluster-announce-bus-port, "16384"]
    volumes:
      - /home/dev/redis/redis.conf:/etc/redis/redis.conf