version: '3'
services:  
  redis01:
    image: redis
    container_name: redis01
    restart: always
    ports:
      - 6379:6379
      - 16379:16379
    entrypoint: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /home/dev/redis_01/redis.conf:/etc/redis/redis.conf
  redis02:
    image: redis
    container_name: redis02
    restart: always
    ports:
      - 6380:6380
      - 16380:16380
    entrypoint: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /home/dev/redis_02/redis.conf:/etc/redis/redis.conf
  redis03:
    image: redis
    container_name: redis03
    restart: always
    ports:
      - 6381:6381
      - 16381:16381
    entrypoint: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /home/dev/redis_03/redis.conf:/etc/redis/redis.conf
  redis04:
    image: redis
    container_name: redis04
    restart: always
    ports:
      - 6382:6382
      - 16382:16382
    entrypoint: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /home/dev/redis_04/redis.conf:/etc/redis/redis.conf
  redis05:
    image: redis
    container_name: redis05
    restart: always
    ports:
      - 6383:6383
      - 16383:16383
    entrypoint: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /home/dev/redis_05/redis.conf:/etc/redis/redis.conf
  redis06:
    image: redis
    container_name: redis06
    restart: always
    ports:
      - 6384:6384
      - 16384:16384
    entrypoint: [redis-server, /etc/redis/redis.conf]
    volumes:
      - /home/dev/redis_06/redis.conf:/etc/redis/redis.conf